// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_kTIrmkH-Xe0nPrfyWDffZ_8kN0Z2Zu0',
    appId: '1:540967880132:web:207a3a1ed5aa058f711091',
    messagingSenderId: '540967880132',
    projectId: 'wibechat-demo',
    authDomain: 'wibechat-demo.firebaseapp.com',
    storageBucket: 'wibechat-demo.firebasestorage.app',
    measurementId: 'G-VCVF880S2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vL1AoiGP6zw-yjELvVhEuEZkU92VUXQ',
    appId: '1:540967880132:android:aac2ea15ca7faf8d711091',
    messagingSenderId: '540967880132',
    projectId: 'wibechat-demo',
    storageBucket: 'wibechat-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCog1G_PijLdDlDfi9nZ4Cx67_cY3SdrrM',
    appId: '1:540967880132:ios:ad25157c32674e63711091',
    messagingSenderId: '540967880132',
    projectId: 'wibechat-demo',
    storageBucket: 'wibechat-demo.firebasestorage.app',
    iosBundleId: 'com.zartek.wibechat.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCog1G_PijLdDlDfi9nZ4Cx67_cY3SdrrM',
    appId: '1:540967880132:ios:b459cb9290d3f408711091',
    messagingSenderId: '540967880132',
    projectId: 'wibechat-demo',
    storageBucket: 'wibechat-demo.firebasestorage.app',
    iosBundleId: 'com.zartek.wibe.call.wibechatCallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_kTIrmkH-Xe0nPrfyWDffZ_8kN0Z2Zu0',
    appId: '1:540967880132:web:ffee60e2e90430e7711091',
    messagingSenderId: '540967880132',
    projectId: 'wibechat-demo',
    authDomain: 'wibechat-demo.firebaseapp.com',
    storageBucket: 'wibechat-demo.firebasestorage.app',
    measurementId: 'G-2E06DRP3DD',
  );
}
